# Site settings
title: CARadOC
subtitle: "PhD Job Fair in Saclay"
url: "https://www.caradoc-paris-saclay.fr" # the base hostname & protocol for your site
baseurl: "" #important: start with /
repository: atacs-centralesupelec/caradoc # required for using JEKYLL_ENV=production 

# Build settings
markdown: kramdown

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "/firebase"
  - "/scripts"
  - "/firestore"
  - "/assets/img/email"
  - "/assets/img/jred"
  - "/assets/css/uglify_airspace.sh"
  - "/assets/img/*.sh"
  - "/assets/img/references"
  - "/assets/img/companies_old"
  - "/assets/img/companies_not_comming"
  - "/assets/img/team/originals"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# How to manage plugins:
# either here in plugins, either in Gemfile, either in _plugins
# Details: https://jekyllrb.com/docs/plugins/installation/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

compress_html:
  ignore:
    envs: ["local"]


# Google analytics
# ga_tracking_id: "UA-XXXX-1"
