exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "/firebase"
  - "/scripts"
  - "/firestore"
  - "/assets/img/email"
  - "/assets/img/jred"
  - "/assets/css/uglify_airspace.sh"
  - "/assets/img/*.sh"
  - "/assets/img/references"
  - "/assets/img/companies_old"
  - "/assets/img/companies_not_comming"
  - "/assets/img/team/originals"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets

repository: atacs-centralesupelec/caradoc
# Site settings
title: CARadOC
subtitle: "PhD Job Fair in Saclay"
url: "https://www.caradoc-paris-saclay.fr" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: "" #important: start with /
#cover: "/assets/img/cover_jred19.png"
#logo: "/assets/img/caradoc_logo.png"
# description: CARaDOC est un forum professionnel pour doctorant et jeunes chercheurs organisé par l'ATACS, l'association des thèsards et amis de CentraleSupélec.
# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  blanklines: true
  endings: all
  startings: [html, head, body]

assets:
  source_maps: false
  destination: "/assets"
  compression: true
  gzip: false
  defaults:
    integrity:
      {css,img,js}: false
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  # --
  # Assets you wish to always have compiled.
  #   This can also be combined with raw_precompile which
  #   copies assets without running through the pipeline
  #   making them ultra fast.
  # --
  precompile: []
  raw_precompile: [
    #
  ]
  # --
  # baseurl: whether or not to append site.baseurl
  # destination: the folder you store them in on the CDN.
  # url: the CDN url (fqdn, or w/ identifier).
  # --
  cdn:
    baseurl: false
    destination: false
    url: null
  # --
  # See lib/jekyll/assets/config.rb
  #   for a list of defaults
  # --
  sources:
    - assets/css
    - assets/img
    - assets/js
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}