description: "CARaDOC is a job fair for PhD Students and young researchers of Paris-Saclay. CARaDOC is organized by volunteer PhD Students and Post-docs of Paris-Saclay."

footer:
  note: "Copyright &copy; &amp; Design by CARaDOC."
