backend:
  name: github
  repo: caradoc-paris-saclay/caradoc 
  branch: 'nocode'

# https://www.netlifycms.org/docs/configuration-options/
site_url: https://www.caradoc-paris-saclay.fr/
logo_url: https://www.caradoc-paris-saclay.fr/assets/img/caradoc_logo_yellow.png
media_folder: "/assets/img"

# slug = clean and standardize new filenames
slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - { label: "Website description", name: "description", widget: 'string' }
      - label: "Home Page"
        name: "homepage"
        file: "_data/homepage.yml"
        fields:
          - { label: "Homepage Title", name: "title", widget: 'string' }
          - { label: "Homepage Title Fontsize (min)", name: "title-font-size-min", widget: 'number' }
          - { label: "Homepage Title Fontsize (max)", name: "title-font-size-max", widget: 'number' }
          - { label: "Homepage Subtitle", name: "subtitle", widget: 'string' }
          - { label: "Homepage SubTitle Fontsize (min)", name: "subtitle-font-size-min", widget: 'number' }
          - { label: "Homepage SubTitle Fontsize (max)", name: "subtitle-font-size-max", widget: 'number' }

  - name: 'blog'
    label: 'News'
    description: "News post manager for publishing about CARaDOC's activity."
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }